### ISSUE TITLE
Styling details

### ISSUE THREAD

**Issue by maria-komarova** [pop-os/cosmic-launcher#11]
Below are details with the styling adjustments for the padding and spacing for the COSMIC Launcher.

![mockups-states](https://user-images.githubusercontent.com/57502897/188937578-14ab5ec0-361b-4e96-943a-a77f66e1db79.png)
![Spacing and Padding](https://user-images.githubusercontent.com/57502897/188937632-512bc731-6822-436c-aa7c-38615a213cad.png)
![Line-item-styling](https://user-images.githubusercontent.com/57502897/188937648-b6704f4d-6e7b-4826-9bf3-1f2079649315.png)

Additional details about colors can be found in Figma: https://www.figma.com/file/KjWhHsdjRU8Ih3Ib1m3t7B/Launcher?node-id=17%3A1116

**Comment by wash2** [comment]
Ok thanks! I'll make the adjustments :+1:
