### ISSUE TITLE
Text copied/cut from launcher is not retained in clipboard

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/cosmic-launcher#118]
If I type some text into the Launcher, then use `Ctrl`-`A` and `Ctrl`-`X` to cut it, I cannot paste it into other apps. This worked in the GNOME COSMIC, and was useful for e.g. needing to transcribe text from an image, since the Launcher is a quick and convenient place to type a small amount of arbitrary text.

This may be a wider issue within COSMIC Epoch since I've noticed the clipboard being lost when I close apps in general, but I'm starting it off here since it's an easy place to replicate the issue.

**Comment by wash2** [comment]
> I've noticed the clipboard being lost when I close apps in general

I believe this is generally a feature of wayland, but the launcher doesn't actually exit when it hides, so it should be able to provide the data it offers through the clipboard after hiding.

**Comment by WatchMkr** [comment]
I've had problem with copy/paste from the Launcher but it seems to be working now.

**Comment by wash2** [comment]
Ya, this should be fixed now.
