### ISSUE TITLE
Running COSMIC Apps don't show up in search results

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-launcher#121]
COSMIC Terminal is shown in the list
![screenshot-2024-05-03-00-06-14](https://github.com/pop-os/cosmic-launcher/assets/3430283/be773abb-f786-4f02-a21a-c1c3bd4834dc)

The running instance is not present when searching for terminal
![screenshot-2024-05-03-00-06-49](https://github.com/pop-os/cosmic-launcher/assets/3430283/853c3bc7-7db3-48a8-a597-b70cf5450f5c)

Firefox correctly shows the running instance and the option to launch a new instance.
![screenshot-2024-05-03-00-07-17](https://github.com/pop-os/cosmic-launcher/assets/3430283/cfaeb3bd-d5d4-49c9-be83-1817b13da54b)

**Comment by wash2** [comment]
I believe this is most likely an issue with how results are ordered by https://github.com/pop-os/launcher. cosmic-launcher just displays what it receives from a search. If you search for the specific title of the COSMIC Terminal window, it does show up.
