### ISSUE TITLE
Bug: Really long search terms blink back and forth with the cursor's blink animation

### ISSUE THREAD

**Issue by leviport** [pop-os/cosmic-launcher#128]
When the cursor disappears, the beginning of the string is shown. When the cursor reappears, the shown portion of the string jumps so that the cursor is visible. Typing that really long string behaves the same way as pasting it, but I pasted it in this video for brevity:

https://github.com/pop-os/cosmic-launcher/assets/13512097/53af7ed9-39df-411b-9b77-026f13341491

**Comment by wash2** [comment]
should be fixed by https://github.com/pop-os/cosmic-launcher/commit/92b871b7676bb44694ddcd34ef5bf3f811e87a28
