### ISSUE TITLE
Shortcut: Alt/Super+Tab behavior

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-launcher#130]
Use the launcher without the search box. Tabbing cycles through the list and letting go focuses the highlighted app.

![Image](https://github.com/pop-os/cosmic-launcher/assets/3430283/94e806be-ff49-4bc1-a519-310927087aff)

The icons to the left can be removed. They're there to represent new or existing instances in the launcher list which doesn't help in this case.

**Comment by senntore** [comment]
A while ago, I thought about using Launcher for Super + Tab as well. But what will you do for window previews, if you do decide to implement it later on?
Will it be visible below the launcher?

**Comment by 16hournaps** [comment]
This is genious!

**Comment by wash2** [comment]
> What will you do for window previews, if you do decide to implement it later on?

I don't think that window previews are planned for alt-tab. Maybe after the first release, the design team will revisit it.

>  Also launcher only shows 8 items, so you'll also have to consider when we have more than 8 windows open.

Ya, I think there might be a few ways of handling this. One is limiting alt-tab to windows on the current workspace, and another is allowing more than 8 items.

I think this issue can now be closed though.

**Comment by senntore** [comment]
@wash2 By the way, was this shortcut enabled for Super+Tab as well? 
Last time I tested it, only Alt+Tab was working.

**Comment by wash2** [comment]
No, it's just alt-tab. I'll make a PR for cosmic-comp that adds it for super-tab too.

**Comment by wash2** [comment]
> @wash2 is window switching within the same app also developed or being considered? I think it's commonly bound to alt/super+` but I have it bound to alt+tab in Pop! stable.

I don't believe it is being developed right now, but I think it would be considered because it is already part of Pop! stable. It's a bit trickier than a simple alt-tab implementation, but I think it could be integrated nicely in the launcher with a couple changes to the [plugin](https://github.com/pop-os/launcher/tree/master/plugins/src/cosmic_toplevel). It would also probably need to be changed to support limiting alt-tab to windows on the current workspace.

**Comment by curiousercreative** [comment]
Just tested this a bit. The "releasing keys' should focus selected window" wasn't working for me when I bound to an alternate key combo (Ctrl + tab). It worked fine on either of the default bindings.

**Comment by curiousercreative** [comment]
Additionally as a feature request, shift alt tab should reverse navigate (same as GNOME)

**Comment by curiousercreative** [comment]
Maybe this isn't the best place for more feedback, but when windows are tiled, they cannot be "raised" using this alt+tab window switcher. Only floating windows can be switched to. For example, if I want Firefox to be fullscreen floating but have a text editor, terminal, etc all tiled, I cannot switch to the set of tiled windows from Firefox.

**Comment by wash2** [comment]
> Maybe this isn't the best place for more feedback, but when windows are tiled, they cannot be "raised" using this alt+tab window switcher. Only floating windows can be switched to. For example, if I want Firefox to be fullscreen floating but have a text editor, terminal, etc all tiled, I cannot switch to the set of tiled windows from Firefox.

I can recreate this, but I don't think this is a launcher issue. Floating windows just seam to be rendered on top of tiled windows, but the keyboard focus does seem to change.

**Comment by curiousercreative** [comment]
More improvements to consider:
- listing more than 8 windows
- listing in order of recently focused

**Comment by curiousercreative** [comment]
@WatchMkr I'm glad to see stories here (along with issues and PRs open) for most improvements, but I'm struggling to find any paper trail for:
- supporting more than 8 windows in the window switcher
- similar keyboard shortcut for window switching, filtered to windows of the same app as current focused window (alt-` commonly)
