### ISSUE TITLE
Space isn't recognized sometimes

### ISSUE THREAD

**Issue by onlyreportingissues** [pop-os/cosmic-launcher#141]
Edit: 

Apparently it has nothing to do with clicking / not clicking on it.

When it runs out of suggestions / results, it won't register the space key anymore.

Spammed asf and space in alternation and when no results were shown anymore, it stopped registering the space key.

_______

Old:

When pressing super, typing something and then pressing space it won't be recognized sometimes. 

One needs to click on the bar for it to recognize it. If one clicks on the desktop, presses super and tries to use space again, it won't work.

**Comment by leviport** [comment]
Can you clarify how you're recreating this? I can't seem to make the same thing happen. I've tried starting on a blank workspace and clicking the desktop as you mentioned, but my space bar works fine every time, whether I type something first or not. Clicking the panel first also has no effect.

**Comment by onlyreportingissues** [comment]
> Can you clarify how you're recreating this? I can't seem to make the same thing happen. I've tried starting on a blank workspace and clicking the desktop as you mentioned, but my space bar works fine every time, whether I type something first or not. Clicking the panel first also has no effect.

Oh, just tried to reproduce it. Apparently it has nothing to do with clicking / not clicking on it.

When it runs out of suggestions, it won't register the space key anymore.

Spammed asf and space in alternation and when no results where shown anymore, it stopped registering the space key.

**Comment by mmstick** [comment]
I'm not seeing that behavior here. I can type a;lskdfj ;laksdj gf;alsdjf ;asjdfl ;lasdjf and it still works.

**Comment by leviport** [comment]
Same here, spacebar just keeps working for me, even when I'm spamming keypresses for several minutes, or pasting in long chunks of text.

**Comment by onlyreportingissues** [comment]
[Video_2024-06-07_15-05-24.webm](https://github.com/pop-os/cosmic-launcher/assets/103491514/96cd7993-4fc6-4afa-8bbe-310a2ff7d5bd)

**Comment by leviport** [comment]
I set my system language to German (Dvorak) and saw the same behavior as English (Dvorak). Same thing on the other Launcher issue you opened this morning.

Can you `apt policy cosmic-launcher` and share what version you have installed?

**Comment by onlyreportingissues** [comment]
> I set my system language to German (Dvorak) and saw the same behavior as English (Dvorak). Same thing on the other Launcher issue you opened this morning.
> 
> Can you `apt policy cosmic-launcher` and share what version you have installed?

```
Name         : cosmic-launcher
Version      : 0.1.0~git20240607.002049.15e5f50
Release      : 1.fc40
Architektur  : x86_64
Größe        : 15 M
Quelle       : cosmic-launcher-0.1.0~git20240607.002049.15e5f50-1.fc40.src.rpm
Paketquelle  : @System
Aus Paketque : copr:copr.fedorainfracloud.org:ryanabx:cosmic-epoch
Zusammenfass : Pop launcher frontend for the COSMIC Desktop Environment
URL          : https://github.com/pop-os/cosmic-launcher
Lizenz       : 0BSD OR MIT OR Apache-2.0 AND Apache-2.0 AND Apache-2.0 OR BSL-1.0 AND Apache-2.0 OR MIT AND
             : Apache-2.0 WITH LLVM-exception AND Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT AND
             : BSD-2-Clause AND BSD-3-Clause AND BSL-1.0 AND CC0-1.0 AND GPL-3.0 AND ISC AND MIT AND MIT AND
             : BSD-3-Clause AND MIT OR Apache-2.0 AND MIT OR Apache-2.0 OR CC0-1.0 AND MIT OR Apache-2.0 OR Zlib
             : AND MIT OR Zlib OR Apache-2.0 AND MPL-2.0 AND Unlicense OR MIT AND Zlib AND Zlib OR Apache-2.0 OR
             : MIT
Beschreibung : Pop launcher frontend for the COSMIC Desktop Environment.

Verfügbare Pakete
Name         : cosmic-launcher
Version      : 0.1.0~git20240607.002049.15e5f50
Release      : 1.fc40
Architektur  : src
Größe        : 92 M
Quelle       : None
Paketquelle  : copr:copr.fedorainfracloud.org:ryanabx:cosmic-epoch
Zusammenfass : Pop launcher frontend for the COSMIC Desktop Environment
URL          : https://github.com/pop-os/cosmic-launcher
Lizenz       : GPL-3.0
Beschreibung : Pop launcher frontend for the COSMIC Desktop Environment.
```

**Comment by onlyreportingissues** [comment]
> I set my system language to German (Dvorak) and saw the same behavior as English (Dvorak). Same thing on the other Launcher issue you opened this morning.
> 
> Can you `apt policy cosmic-launcher` and share what version you have installed?

![screenshot-2024-06-07-13-33-29](https://github.com/pop-os/cosmic-launcher/assets/103491514/f95f3358-c6b6-4080-90eb-14ad4e71cf93)

I didnt use Dvorak, just German *the first one(.

**Comment by leviport** [comment]
Yeah I tried that one too, no change. All keyboard layouts are performing the same for me. My launcher version was slightly behind yours, but I've updated and again see no change in behavior.

**Comment by atagen** [comment]
I can recreate both behaviours - space works consistently when the text cursor is "in" the input, but when it isn't, the launcher still captures alphanumeric keyboard input and ignores spaces. If I had to guess it's being discarded around [here](https://github.com/pop-os/cosmic-launcher/blob/99a3773e226545e8c4f4216df0f0bf5ee46f2928/src/app.rs#L915).

**Comment by leviport** [comment]
Alright, I can now recreate this reliably on this version:
```
$ apt policy cosmic-launcher
cosmic-launcher:
  Installed: 0.1.0~1718100953~22.04~51f3f92
  Candidate: 0.1.0~1718100953~22.04~51f3f92
  Version table:
 *** 0.1.0~1718100953~22.04~51f3f92 1002
       1002 http://apt.pop-os.org/staging/master jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     0.1.0~1716572311~22.04~7c207e2 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
```
