### ISSUE TITLE
[Calculator] Plus operator only entered on the first keystroke

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-launcher#144]
1. Use Super to activate the launcher
2. type a number then +
3. type a number then + (the second plus will not show up)
4. You have to click in the Launcher to enter any more plus symbols.

Perhaps related to the Shift modifier. This does not occur with minus.

"Enter" also doesn't work correctly
1. Enter a number such as 10/5
2. Press Enter, the result won't be in the launcher field

**Comment by mmstick** [comment]
Could be related to #141
