### ISSUE TITLE
Search results are different in COSMIC than GNOME. COSMIC results are incorrect.

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-launcher#145]
1. Open Firefox with the Launcher
2. Open the Launcher
3. Type "Files" 

The Firefox tab name is first in the list when COSMIC Files or Nautilus Files should be first. In GNOME, the Launcher list COSMIC File/Nautilus first.

**Comment by mmstick** [comment]
https://github.com/pop-os/launcher/pull/219 may have improved this

**Comment by wiiznokes** [comment]
> [pop-os/launcher#219](https://github.com/pop-os/launcher/pull/219) may have improved this

I don't think so, it seems related to this issue https://github.com/pop-os/launcher/issues/217

This could explain the difference between cosmic and cosmic-gnome:

> This problem is also present in the cosmic-launcher UI. The app will try to gather all plugin search result together, by sorting the Indice field.

**Comment by curiousercreative** [comment]
I'll add another reproduction (with latest packages installed and reproducible today):
1. With thunderbird installed
1. Open Firefox (and Chromium if you have it installed)
1. search for "thu", "thun", or "thund"
    ER/AR: Thunderbird is the top result, firefox and chromium are not even on the list
1. search for "thunde"
    ER: Thunderbird to be the top result
    AR: Firefox is top result followed by Thunderbird
1. search for "thunder"
    ER: Thunderbird to be the top result
    AR: Firefox is top result followed by Chromium, then Thunderbird
1. search for "thunderb", "thunderbi", "thunderbir", or "thunderbird"
    ER/AR: Thunderbird is the top result

**Comment by git-f0x** [comment]
I think this may have been mostly fixed, since both mentioned ways to reproduce seem to behave as expected now.
There is some weirdness on this specific page, if it's the currently focused tab: searching "thu" displays thunderbird as the top result, but "thun" and "thund" display Firefox again.
On e.g. New Tab, Thunderbird is the top result at "th", and stays the top result when continuing to type the name.

**Comment by WatchMkr** [comment]
I'm going to reopen and move to alpha 2. I find the results inefficient and they weren't before. The top result is almost never the intended app any longer.

**Comment by curiousercreative** [comment]
Not sure if there was a release that addressed this, but I've noticed that yesterday and today the results are much better!

**Comment by WatchMkr** [comment]
Same! Closing.
