### ISSUE TITLE
minimized windows like in gnome

### ISSUE THREAD

**Issue by soloturn** [pop-os/cosmic-launcher#160]
if pressing windows key would display minimized windows like in gnome it would be extremely cool to choose which window to switch to. if the windows become too small it would not matter to scroll a little, important would be windows contents still can be recognized to identify which window it is one wants.

like in gnome, starting to type would search a window or program to start. 

pressing 2 times windows key woudl search programs and web.

**Comment by Kartonrealista** [comment]
> if pressing windows key would display minimized windows like in gnome it would be extremely cool to choose which window to switch to. if the windows become too small it would not matter to scroll a little, important would be windows contents still can be recognized to identify which window it is one wants.

You mean workspace view? That's already there under Super ("windows key") + w.

> like in gnome, starting to type would search a window or program to start.

That's already the function of the launcher.

> pressing 2 times windows key woudl search programs and web.

That won't happen.

**Comment by soloturn** [comment]
the launcher uses only a small portion of the screen ,which is ugly. as cosmic knows tiling, one time super key could also tile all windows. why one would need 2 keys like super-w to have that :) there is no other basic function than start an app or find an open one. gnome showed it can be done with one key, and they were with gnome3 simplicity masters.

**Comment by WatchMkr** [comment]
Thank you for the suggestion. We do not intend to reproduce the GNOME UX in COSMIC. However, the applet system could be used for others to do so if they're interested.
