### ISSUE TITLE
[ENHANCEMENT] Use Alt + [Number] Instead of Ctrl + [Number] for App Switcher in Cosmic

### ISSUE THREAD

**Issue by iamkartiknayak** [pop-os/cosmic-launcher#168]
## Description:
The app switcher in Cosmic DE currently requires holding Alt while using Ctrl + [Number] to switch between apps. It would be more intuitive and efficient if the keybinding were changed to Alt + [Number] directly, allowing users to switch to the desired window by simply pressing the number key while Alt is held down. Since the app switcher is already in focus during use, this change would not interfere with background windows and would streamline the app-switching process.

**Comment by WatchMkr** [comment]
Duplicate https://github.com/pop-os/cosmic-launcher/issues/162
