### ISSUE TITLE
[Feature Request] Custom plugins/settings

### ISSUE THREAD

**Issue by djohnson1865** [pop-os/cosmic-launcher#179]
Having a setting/configuration ability in which we could create our own modules for the search would be amazing.
 
I'm thinking this could be effectively a dmenu-like interface which takes a script as an input parameter and just feeds the menu input into said script similar to how dmenu/rofi function.

**Comment by bbb651** [comment]
This is already a thing, see [pop-launcher](https://github.com/pop-os/launcher?tab=readme-ov-file#plugin-directories)
