### ISSUE TITLE
[Bug] Not launching applications nor responding to queries

### ISSUE THREAD

**Issue by Elias-Graf** [pop-os/cosmic-launcher#192]
Sometimes, the launcher seems to refuse to launch or actually perform the search. It happens randomly, but I seem to be able to trigger the issue somewhat reliably using the word "teams", which is quite unfortunate for work related purposes, lol.

https://github.com/user-attachments/assets/f4d14eef-dcb5-447b-a126-bee28f9f649f

**Comment by Elias-Graf** [comment]
#191 _could_ be related

**Comment by fleefie** [comment]
Definitely feel like they are, it's the same behavior that I was experiencing.

**Comment by wramalho** [comment]
I have the same issue since August, I believe

**Comment by fleefie** [comment]
This seemed to have been ficed in https://github.com/pop-os/launcher/pull/241 🎉

**Comment by Elias-Graf** [comment]
Ah, yes it seems fixed, nice! Thanks for letting me know!
