### ISSUE TITLE
Typing "lib" and variations of "scr" causes crashes

### ISSUE THREAD

**Issue by TheKamboy** [pop-os/cosmic-launcher#213]
I wanted to check if my system had libreoffice installed, so I searched it through cosmic launcher, which caused a crash when typing "lib".
Typing "scr" or replacing the r with certain letters also causes a crash. If anyone can tell me how to get backtraces working with this, since I can't figure out how to get backtraces to work with cosmic launcher.

Oh yeah, at the time of writing this, "sc" also causes crashes now as well. Wonderful.

**Comment by mmstick** [comment]
Which version of pop-launcher and cosmic-launcher?

**Comment by smsteward** [comment]
I have this issue as well, but with different character combinations. If I type "pr" or "po" into cosmic-launcher (usually to open Proton apps or Portmaster), cosmic-launcher exits immediately. I'm only able to launch those apps via the launcher by typing just the first character, and scrolling through the resulting menu or by pressing the Ctrl+number from the launcher menu. I'm using `cosmic-launcher-git` and `pop-launcher-git` from the AUR.

```
$ pacman -Qi cosmic-launcher-git
Name            : cosmic-launcher-git
Version         : 1.0.0.alpha.2.r3.g27ab200-1
Description     : Layer Shell frontend for Pop Launcher.
Architecture    : x86_64
URL             : https://github.com/pop-os/cosmic-launcher
Licenses        : GPL-3.0-or-later
Groups          : None
Provides        : cosmic-launcher
Depends On      : hicolor-icon-theme  libxkbcommon  pop-launcher-git  wayland
Optional Deps   : None
Required By     : cosmic-session-git
Optional For    : None
Conflicts With  : cosmic-launcher
Replaces        : None
Installed Size  : 22.15 MiB
Packager        : Unknown Packager
Build Date      : Thu 24 Oct 2024 10:24:48 PM EDT
Install Date    : Thu 24 Oct 2024 10:25:49 PM EDT
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : None

$ pacman -Qi pop-launcher-git
Name            : pop-launcher-git
Version         : 1.2.4.r0.gfca3b25-1
Description     : Modular IPC-based desktop launcher service
Architecture    : x86_64
URL             : https://github.com/pop-os/launcher
Licenses        : MPL-2.0
Groups          : None
Provides        : pop-launcher
Depends On      : dbus  fd  libqalculate  libegl  libxkbcommon  pop-icon-theme-git  sh
                  xdg-utils
Optional Deps   : pop-shell-plugin-system76-power
Required By     : cosmic-launcher-git
Optional For    : None
Conflicts With  : pop-launcher
Replaces        : None
Installed Size  : 9.76 MiB
Packager        : Unknown Packager
Build Date      : Fri 18 Oct 2024 06:28:59 PM EDT
Install Date    : Fri 18 Oct 2024 06:29:46 PM EDT
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : None
```

**Comment by TheKamboy** [comment]
> Which version of pop-launcher and cosmic-launcher?

I'm using the git versions of both programs, which I installed from the Chaotic AUR.

pop-launcher:
```
Name            : pop-launcher-git
Version         : 1.2.4.r0.gfca3b25-1
Description     : Modular IPC-based desktop launcher service
Architecture    : x86_64
URL             : https://github.com/pop-os/launcher
Licenses        : MPL-2.0
Groups          : None
Provides        : pop-launcher
Depends On      : dbus  fd  libqalculate  libegl  libxkbcommon  pop-icon-theme-git  sh  xdg-utils
Optional Deps   : pop-shell-plugin-system76-power
Required By     : cosmic-launcher-git
Optional For    : None
Conflicts With  : pop-launcher
Replaces        : None
Installed Size  : 9.67 MiB
Packager        : Garuda Builder <team@garudalinux.org>
Build Date      : Fri 18 Oct 2024 10:57:02 AM PDT
Install Date    : Fri 18 Oct 2024 06:15:55 PM PDT
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : SHA-256 Sum  Signature
```

cosmic-launcher:
```
Name            : cosmic-launcher-git
Version         : 1.0.0.alpha.2.r3.g27ab200-1
Description     : Layer Shell frontend for Pop Launcher.
Architecture    : x86_64
URL             : https://github.com/pop-os/cosmic-launcher
Licenses        : GPL-3.0-or-later
Groups          : None
Provides        : cosmic-launcher
Depends On      : hicolor-icon-theme  libxkbcommon  pop-launcher-git  wayland
Optional Deps   : None
Required By     : cosmic-session-git
Optional For    : None
Conflicts With  : cosmic-launcher
Replaces        : None
Installed Size  : 22.20 MiB
Packager        : Garuda Builder <team@garudalinux.org>
Build Date      : Wed 23 Oct 2024 08:38:27 AM PDT
Install Date    : Thu 24 Oct 2024 05:05:14 PM PDT
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : SHA-256 Sum  Signature
```

**Comment by TheKamboy** [comment]
> I have this issue as well, but with different character combinations. If I type "pr" or "po" into cosmic-launcher (usually to open Proton apps or Portmaster), cosmic-launcher exits immediately. I'm only able to launch those apps via the launcher by typing just the first character, and scrolling through the resulting menu or by pressing the Ctrl+number from the launcher menu. I'm using `cosmic-launcher-git` and `pop-launcher-git` from the AUR.
> 
> ```
> $ pacman -Qi cosmic-launcher-git
> Name            : cosmic-launcher-git
> Version         : 1.0.0.alpha.2.r3.g27ab200-1
> Description     : Layer Shell frontend for Pop Launcher.
> Architecture    : x86_64
> URL             : https://github.com/pop-os/cosmic-launcher
> Licenses        : GPL-3.0-or-later
> Groups          : None
> Provides        : cosmic-launcher
> Depends On      : hicolor-icon-theme  libxkbcommon  pop-launcher-git  wayland
> Optional Deps   : None
> Required By     : cosmic-session-git
> Optional For    : None
> Conflicts With  : cosmic-launcher
> Replaces        : None
> Installed Size  : 22.15 MiB
> Packager        : Unknown Packager
> Build Date      : Thu 24 Oct 2024 10:24:48 PM EDT
> Install Date    : Thu 24 Oct 2024 10:25:49 PM EDT
> Install Reason  : Installed as a dependency for another package
> Install Script  : No
> Validated By    : None
> 
> $ pacman -Qi pop-launcher-git
> Name            : pop-launcher-git
> Version         : 1.2.4.r0.gfca3b25-1
> Description     : Modular IPC-based desktop launcher service
> Architecture    : x86_64
> URL             : https://github.com/pop-os/launcher
> Licenses        : MPL-2.0
> Groups          : None
> Provides        : pop-launcher
> Depends On      : dbus  fd  libqalculate  libegl  libxkbcommon  pop-icon-theme-git  sh
>                   xdg-utils
> Optional Deps   : pop-shell-plugin-system76-power
> Required By     : cosmic-launcher-git
> Optional For    : None
> Conflicts With  : pop-launcher
> Replaces        : None
> Installed Size  : 9.76 MiB
> Packager        : Unknown Packager
> Build Date      : Fri 18 Oct 2024 06:28:59 PM EDT
> Install Date    : Fri 18 Oct 2024 06:29:46 PM EDT
> Install Reason  : Installed as a dependency for another package
> Install Script  : No
> Validated By    : None
> ```

Interestingly, I don't have the same issue.

**Comment by TheKamboy** [comment]
I also discovered that `gim` and `gn` also causes cosmic-launcher to crash.

**Comment by wash2** [comment]
This seems like a bug from an older version of the launcher. Could you try using the latest version of the [launcher](https://github.com/pop-os/launcher)? The AUR version seems like it was last updated before the fix https://github.com/pop-os/launcher/commit/476a8fb44564b7075adf2c3b74bad758f6582747

**Comment by TheKamboy** [comment]
> This seems like a bug from an older version of the launcher. Could you try using the latest version of the [launcher](https://github.com/pop-os/launcher)? The AUR version seems like it was last updated before the fix https://github.com/pop-os/launcher/commit/476a8fb44564b7075adf2c3b74bad758f6582747

I will when I can, as I'm currently busy with school. Thanks for letting me know.

**Comment by TheKamboy** [comment]
@wash2 The latest version didn't seem to do anything.

**Comment by TheKamboy** [comment]
Ok, for some reason, sometimes it doesn't bug out when trying to search for gimp, but still has issues with trying to search for libreoffice

**Comment by curiouslad** [comment]
spo also crash on cosmic

**Comment by wash2** [comment]
> @wash2 The latest version didn't seem to do anything.

How did you install the latest version? 

> spo also crash on cosmic

The AUR version is still out of date and I don't think this is an issue in more recent versions. What version are you using @curiouslad? I'd be happy to look into it some more with a bit more details.

**Comment by curiouslad** [comment]
@wash2  I am on fedora the version of launcher it says 1.0.0~alpha.3^git20241126.6322a99. I can provide logs if that would help, but i am not sure where to find them

**Comment by wash2** [comment]
@curiouslad I believe that is referencing https://github.com/pop-os/cosmic-launcher/commit/6322a99d177b5af4bd648900b9258d8b2a39d5bd which should be a different package than the one that I believe was the source of the issue. Could you maybe check the version for pop-launcher?

**Comment by wash2** [comment]
Hmm actually, I'll push a quick update to the pop-launcher crate used in cosmic-launcher, which might fix the issue.

**Comment by avnyu** [comment]
rebuilt on arch, ```cosmic-launcher-git 1.0.0.alpha.3.r3.g9324e9e-1``` and ```pop-launcher-git 1.2.4.r0.gfca3b25-1```, still have the issues, mine is when typing 'gi' or when backspace 'gi' to 'g', also happened on newly created user

**Comment by wiiznokes** [comment]
i'm having a crash with "yt" too. My guess is that it's related to https://github.com/iced-rs/iced/pull/2651

**Comment by TheKamboy** [comment]
i completely forgot about this issue lol. it is fixed for me since the update was done. thanks!

**Comment by Legolaszstudio** [comment]
Same issue here on cachyos, but with `sp`.

https://github.com/user-attachments/assets/bdcceab3-f198-4f7d-95cf-950ff34c79b8

Version:
```
❯ uname -r
7.0.3-1-cachyos
❯ pacman -Qi cosmic-launcher
Installed From  : cachyos-extra-v4
Name            : cosmic-launcher
Version         : 1:1.0.11-1.1
❯ cosmic-launcher --version
cosmic-launcher 1.0.3
```

```
❯ journalctl --user --since "5 minutes ago" | grep -i cosmic-launcher
máj 04 10:01:00 cachyos-novy-dell cosmic-session[1091]: process ' WAYLAND_DISPLAY=wayland-1 DISPLAY=:1 XDG_SESSION_TYPE=wayland cosmic-launcher ' failed with code 101
máj 04 10:01:00 cachyos-novy-dell cosmic-session[1091]: cosmic-launcher exited with error 101
máj 04 10:01:00 cachyos-novy-dell cosmic-session[1091]: sleeping for 9ms before restarting process cosmic-launcher (restart 0)
máj 04 10:01:00 cachyos-novy-dell systemd[1056]: cosmic-launcher.scope: Consumed 17.633s CPU time over 2h 36min 52.299s wall clock time, 212.8M memory peak.
máj 04 10:01:00 cachyos-novy-dell cosmic-session[1091]: restarted process ' WAYLAND_DISPLAY=wayland-1 DISPLAY=:1 XDG_SESSION_TYPE=wayland cosmic-launcher ', now at 1 restarts
máj 04 10:01:00 cachyos-novy-dell cosmic-launcher[13196]: Failed to activate another instance
máj 04 10:01:00 cachyos-novy-dell systemd[1056]: Started cosmic-launcher.scope.
máj 04 10:01:56 cachyos-novy-dell cosmic-session[1091]: process ' WAYLAND_DISPLAY=wayland-1 DISPLAY=:1 XDG_SESSION_TYPE=wayland cosmic-launcher ' failed with code 101
máj 04 10:01:56 cachyos-novy-dell cosmic-session[1091]: cosmic-launcher exited with error 101
máj 04 10:01:56 cachyos-novy-dell cosmic-session[1091]: sleeping for 0ms before restarting process cosmic-launcher (restart 1)
máj 04 10:01:56 cachyos-novy-dell systemd[1056]: cosmic-launcher.scope: Consumed 1.004s CPU time over 56.497s wall clock time, 106.8M memory peak.
máj 04 10:01:56 cachyos-novy-dell cosmic-session[1091]: restarted process ' WAYLAND_DISPLAY=wayland-1 DISPLAY=:1 XDG_SESSION_TYPE=wayland cosmic-launcher ', now at 2 restarts
máj 04 10:01:56 cachyos-novy-dell cosmic-launcher[13330]: Failed to activate another instance
máj 04 10:01:56 cachyos-novy-dell systemd[1056]: Started cosmic-launcher.scope.
máj 04 10:02:36 cachyos-novy-dell cosmic-session[1091]: process ' WAYLAND_DISPLAY=wayland-1 DISPLAY=:1 XDG_SESSION_TYPE=wayland cosmic-launcher ' failed with code 101
máj 04 10:02:36 cachyos-novy-dell cosmic-session[1091]: cosmic-launcher exited with error 101
máj 04 10:02:36 cachyos-novy-dell cosmic-session[1091]: sleeping for 0ms before restarting process cosmic-launcher (restart 2)
máj 04 10:02:36 cachyos-novy-dell systemd[1056]: cosmic-launcher.scope: Consumed 2.212s CPU time over 39.874s wall clock time, 105.6M memory peak.
máj 04 10:02:36 cachyos-novy-dell cosmic-session[1091]: restarted process ' WAYLAND_DISPLAY=wayland-1 DISPLAY=:1 XDG_SESSION_TYPE=wayland cosmic-launcher ', now at 3 restarts
máj 04 10:02:36 cachyos-novy-dell cosmic-launcher[13458]: Failed to activate another instance
máj 04 10:02:36 cachyos-novy-dell systemd[1056]: Started cosmic-launcher.scope.
```
