### ISSUE TITLE
Launcher Comparision 

### ISSUE THREAD

**Issue by n3m0-22** [pop-os/cosmic-launcher#27]
This is a feature comparison between Pop Launcher and Cosmic Launcher.

|Feature List                                                               |Pop Launcher|Cosmic Launcher   |Issues                                                                                                                                                     |
|---------------------------------------------------------------------------|------------|------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------|
|calc                                                                       |working     |working           | can't [Ctrl-C copy active option and close window](https://github.com/pop-os/shell/pull/1587)                                                                                                                                                          |
|desktop_entries                                                            |working     |working           |                                                                                                                                                           |
|files                                                                      |working     |partially working |no tab auto complete                                                                                   |
|find                                                                       |working     |working           |                                                                                                                                                           |
|pulse                                                                      |working     |partially working |volume changes are not equal to 5% as stated in the launcher (e.g.,  vol=100 down 5% brings it to 86 not 95), volume up is not working when starting from 0|
|recent                                                                     |working     |working           |                                                                                                                                                           |
|scripts                                                                    |working     |partially working       | user local scripts are not detected                                                                                                             |
|terminal                                                                   |working     |working (`t:` and `:`)|                                                                                                                                                           |
|web                                                                        |working     |working           |no icon                                                                                                                                                    |
|suspend                                                                    |working     |working           |stops working sometime after suspend                                                                                                                       |
|restart                                                                    |working     |working           |                                                                                                                                                           |
|lock                                                                       |working     |not working       |no lock screen                                                                                                                                             |
|shutdown                                                                   |working     |working           |                                                                                                                                                           |
|options “?”                                                                |working     |working       |                                                                                                                              |
|when searching the nth item launches with keyboard `Ctrl`+`n` (e.g., `Ctrl`+`1`)                      |working     |working           |                                                                                                                                                           |
|switching open windows                                                     |working     |working           |                                                                                                                                                           |
|search settings                                                            |working     |not working       |                                                                                                                                                           |
|all windows on all workspaces appear                                       |working     |working           |                                                                                                                                                           |
|choosing an app on another workspace moves workspaces and focus to that app|working     |working           |                                                                                                                                                           |
|launching an application works                                             |working     |working           |                                                                                                                                                           |
|typing text and then removing it will re-show those windows                |working     |working           |                                                                                                                                                           |
|search works for applications and windows                                  |working     |working           |                                                                                                                                                           |
|the overlay hint correctly highlights the selected window                  |working     |not working       |no change in highlighted window                                                                                                                            |
|open windows are sorted above applications (e.g., "web browser")           |working     | working       |                                                                                                   |
|cal returns Calendar and Calculator before Color                           |working     |working           |                                                                                                                                                           |
|pops returns Popsicle first                                                |working     |working           |                                                                                                                                                           |
|shop returns the Pop!_Shop first                                           |working     |working           |                                                                                                                                                           |
|opens with `Super` + `/` and opens with `Super` key                              |working     |working |                                                                                                                          |
|first item is highlighted by default (starting launcher or searching)                               |working     |not working 
|navigate/select with Emacs or Vim keybindings                               |working     |working                                                                                                                         |
|                                                                           |            |                  |                                                                                                                                                           |
|<b>Other issues</b>                                                               |            |                  |                                                                                                                                                           |                                                                                                                                                           |
|Key presses repeat sometime similar to sticky keys                         |            |                  |                                                                                                                                                           |

**Comment by wash2** [comment]
> open windows are sorted above applications (e.g., "web browser")

Hmm that is strange this seems to be working fine for me. Do you have the latest installed for pop-launcher & cosmic-launcher?

**Comment by wash2** [comment]
> Key presses repeat sometime similar to sticky keys

Ya, thankfully this issue will soon be fixed :)

**Comment by WatchMkr** [comment]
I didn't know I could toggle mute from the Launcher. That's nice.

**Comment by leviport** [comment]
Oh, I think I found another: `Ctrl` + `n` and `Ctrl` + `p` (Emacs nav shortcuts) move selection down and up, respectively, in the current Pop launcher, but not in current cosmic-launcher.

**Comment by wash2** [comment]
> Oh, I think I found another: Ctrl + n and Ctrl + p (Emacs nav shortcuts) move selection down and up, respectively, in the current Pop launcher, but not in current cosmic-launcher.

should be resolved by https://github.com/pop-os/cosmic-launcher/pull/30 :)

**Comment by n3m0-22** [comment]
> > Oh, I think I found another: Ctrl + n and Ctrl + p (Emacs nav shortcuts) move selection down and up, respectively, in the current Pop launcher, but not in current cosmic-launcher.
> 
> should be resolved by #30 :)

This seems to have the Emacs shortcuts working but not the Vim. I am also now seeing the launcher at the top of the screen near where notifications show.

**Comment by wash2** [comment]
> This seems to have the Emacs shortcuts working but not the Vim.

Ok I'll add the vim bindings today :sweat_smile: 

> I am also now seeing the launcher at the top of the screen near where notifications show.

Ya this matches current designs. The intent is to allow space for a future on-screen keyboard.

**Comment by XV-02** [comment]
I just wanted to revisit this, given how long it has been since this was formally looked at. 

The original findings (table in the top comment) appear to be correct still, save perhaps for the "recent" function, which didn't seem to work for me in either launcher.

**Comment by wash2** [comment]
> not launching with only Super key

This has been resolved, hasn't it?

**Comment by XV-02** [comment]
It has. Good catch. I'll update that.
