### ISSUE TITLE
Different behaviour with life time of scripts compared to pop-shell

### ISSUE THREAD

**Issue by maru-sama** [pop-os/cosmic-launcher#46]
Hello,

I am currently test driving this launcher in a sway environment. What I am seeing is that compared to pop-shell. pop-launcher is started at the beginning  and keeps all the plugins running once they are started. 

One of my plug-in is currently caching the results it receives from a  web search to make filtering faster. This works just fine in pop-shell since once the launcher is closed the script is closed as well.

With cosmic-launcher it is not closed, so even if the launcher is closed and reopened my script will still use the cached values. 
Right now i use a timer to invalidate the cache but this is more of a workaround.
Would it be possible to either:

 * close the plugins once the launcher is closed. I think this is a little bit too much and requires several changes looking at the current setup
 * Send a "Close" message to the plugins so they are aware that the window has been closed and therefore invalidate their state

I think the second option would be the best solution because then it is up to the plugin to decide what to do in this case.

**Comment by mmstick** [comment]
My last PR made the pop-launcher close when the dialog is closed. Is this not happening anymore?

**Comment by maru-sama** [comment]
I tried it with the latest commit. For testing I start cosmic-launcher in a terminal, then I send the dbus toggle command. The popup opens and I see that also pop-laucnher gets started. If I then trigger my plugin it gets loaded as well. If I then hit escape to close the window pop-launcher is still running.

**Comment by mmstick** [comment]
Then [this](https://github.com/pop-os/cosmic-launcher/blob/master_jammy/src/subscriptions/launcher.rs#L105-L111) may not be getting called when the dialog is closed.

**Comment by wash2** [comment]
> My last PR made the pop-launcher close when the dialog is closed. Is this not happening anymore?

Yes I had to revert it (probably temporarily) as the toplevel plugin didn't display active windows if it is restarted.

**Comment by maru-sama** [comment]
I see that this commit is in  [advanced-text_jammy](https://github.com/pop-os/cosmic-launcher/compare/advanced-text_jammy) but not in current HEAD. 
What is the branch to use right now for testing?

**Comment by wash2** [comment]
> What is the branch to use right now for testing

To my knowledge, master_jammy should be most up to date with changes if that’s what you’re asking

**Comment by maru-sama** [comment]
> I see that this commit is in [advanced-text_jammy](https://github.com/pop-os/cosmic-launcher/compare/advanced-text_jammy) but not in current HEAD. What is the branch to use right now for testing?

I just trued advanced-text_jammy and there it works "normally". Pop-launcher gets closed once cosmic-launcher is hidden.

**Comment by wash2** [comment]
I've made a PR which should send the close message again. Could you give that a try and let me know?

**Comment by maru-sama** [comment]
> I've made a PR which should send the close message again. Could you give that a try and let me know?

Hi, this makes it actually worse. After closing the popup pop-launcher is still running and subsequent dbus toggle calls fail. The only way to get it running again is to kill cosmic-launcher and start it again.

**Comment by wash2** [comment]
Ok lol, I’ll restart them again too. Thanks 😅

**Comment by wash2** [comment]
After testing the PR in sway, I believe there is some other issue with creating the layer shell surface on sway. It seems to work well in cosmic-comp. But as far as I can tell, the toggle calls are received, and the launcher tries to create the surface. I'll keep looking into it, but until i figure out what the issue is, i hope the advanced-text branch works well for you.

**Comment by maru-sama** [comment]
Hello, I can confirm that the last commits fix the issue I had for me. Toggle now always works and pop-launcher gets closed once the pop-up closes. Thanks a lot.
