### ISSUE TITLE
Refresh applications launcher

### ISSUE THREAD

**Issue by vanessakindell** [pop-os/cosmic-launcher#74]
Any time software is installed via Wine or otherwise adds additional .desktop files to the applications folder, the list doesn't update and as far as I can tell, there's no way to tell it to refresh. The only way I've managed to get it to is by logging out and logging back in. For obvious reasons, this is less than ideal. Ideally this would be accomplished by either a refresh button in the launcher window itself or some kind of key combination.

**Comment by wash2** [comment]
That is strange that it doesn't update to include your newly installed applications. What version do you have installed? If you installed through apt, could you share the output of `apt show cosmic-launcher`?

When I install a flatpak it does update to include them. Does it update when you install a flatpak and do you know where the desktop files for applications that don't show are being installed?

You could restart the launcher using `pkill -x cosmic-launcher` (if you are using cosmic-session, it will be automatically restarted). And if you want to add a shortcut, you can copy https://github.com/pop-os/cosmic-comp/blob/master_jammy/config.ron from cosmic-comp and save it to `$XDG_CONFIG_HOME/cosmic-comp/config.ron`. If XDG_CONFIG_HOME is not set, it is` ~/.config`. You could copy the format of the other shortcuts in `config.ron`. It will change as work continues on cosmic-comp though.

**Comment by vanessakindell** [comment]
UPDATE: Turns out I'm not yet on the cosmic version of the launcher. I'm on whatever the hybrid gnome-cosmic that shipped with 22.04.
