### ISSUE TITLE
Cursor placement wrong during certain searches

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/cosmic-launcher#77]
If I try to search for `firefox` (or `files`), the cursor jumps back to the beginning of the input box after `fi`, then remains one letter behind the end of the string (this doesn't actually affect where text is input):

https://github.com/pop-os/cosmic-launcher/assets/7199422/5e0387a7-84f0-49af-a77d-e9e4990cc4be

This doesn't seem to happen with some other search strings (e.g. `cosmic`).

**Comment by wash2** [comment]
This seems like it is an issue with text measurement in iced and I can recreate it in the todos example. I'll see if I can find a fix though :)

**Comment by wash2** [comment]
I believe this should be fixed now?
