### ISSUE TITLE
After attempting to launch from terminal, no results every other search

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/cosmic-launcher#8]
Version: [a1270e3](https://github.com/pop-os/cosmic-launcher/commit/a1270e367c85c250919123ffcc372c3c03f6f382)

When I first log into the COSMIC session, search results work as expected.

If I open a terminal and run `cosmic-launcher`, the command completes with no output; from then on, every other search returns no results.

Logs of running the command, performing one successful search, and performing one non-working search: [launcher-issue-1.txt](https://github.com/pop-os/cosmic-launcher/files/9277235/launcher-issue-1.txt)

Running the command additional times doesn't seem to affect the behavior (e.g. launching `cosmic-launcher` again doesn't make it work 1 in 3 times, it still works 1 in 2 times.)

Ideally, search behavior should be consistent, and running the command should handle an already-running process and/or show an appropriate message instead of silently breaking results. (I found this while trying to figure out how to start the launcher, since plain `Super` wasn't working, but later figured out that it requires `Super` + `/`.)

**Comment by wash2** [comment]
Currently, the launcher does not handle already running processes while in Cosmic Comp. It won't until I add support for the toplevel protocol to the launcher service. I'll look into why no results are being returned though!
