### ISSUE TITLE
Closing launcher with Super + / and re-opening can make the launcher briefly reappear with previous search results

### ISSUE THREAD

**Issue by leviport** [pop-os/cosmic-launcher#9]
### Summary:
After typing a search term, then closing the launcher with Super + /, then re-opening the launcher with Super + / again, the launcher briefly shows the results from the last search query when it reappears.

### Steps to reproduce:
- Open launcher with Super + /
- Type a search query so that some results are displayed
- Close the launcher with Super + /
- Re-open the launcher with Super + /

### Expected behavior:
When the launcher reappears, it should not show any results.

### Version:
```
cosmic-launcher:
  Installed: 0.1.0~1660784291~22.04~14a8eca
  Candidate: 0.1.0~1660784291~22.04~14a8eca
  Version table:
 *** 0.1.0~1660784291~22.04~14a8eca 1002
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1002 http://apt.pop-os.org/staging/master jammy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by wash2** [comment]
Ok, I'm able to replicate this and I know the issue. Thanks!

**Comment by leviport** [comment]
Looks like this is fixed now!
